apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mikey-daemonset
  labels:
    app: nginx
spec:
  minReadySeconds: 5
  selector:
    matchLabels: 
      app: nginx
  template:
    metadata:
      name: mikey-daemonpod
      labels:
        app: nginx
    spec:
      containers: 
        - name: mikey-cont3
          image: alpine
          command:
            - sleep
          args:
            - 1d
