apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikey-deployment
  labels:
    app: nginx
spec:
  minReadySeconds: 5
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: mikey-deploypod
      labels:
        app: nginx
    spec:
      containers:
        - name: mikey-deploycont
          image: jenkins/jenkins:2.401.2
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mikey-svc
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - targetPort: 8080
      port: 35000
  type: LoadBalancer