apiVersion: v1 
kind: Pod
metadata:
  name: mikey-pod
  labels:
    app: nginx
spec:
  initContainers:
    - name: initcontainer-1
      image: alpine
      command:
        - sleep
      args:
        - 30s
  containers:
    - name: mikey-cont
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
  