apiVersion: v1
kind: Pod
metadata:
  name: mikey-live
  labels:
    app: nginx
spec:
  containers: 
    - name: mikey-cont2
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10