---
apiVersion: v1
kind: Pod
metadata:
  name: mikey-pod
  labels:
    app: nginx
spec:
  containers:
    - name: mikey-cont
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      
  