---
apiVersion: v1
kind: Pod
metadata:
  name: mikey-pod
  labels:
    app: nginx
spec:
  containers:
    - name: mikey-cont
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: mikey-svc
  labels: 
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - nodePort: 32001
      port: 35000
      targetPort: 80
  type: NodePort