apiVersion: v1
kind: Pod
metadata: 
  name: mikey-pod
  labels:
    app: nginx
spec:
  containers:
    - name: mikey-cont1
      image: alpin
      command:
        - sleep
      args:
        - 50s
  restartPolicy: OnFailure