apiVersion: v1
kind: Pod
metadata: 
  name: mikey-pod
  labels:
    app: nginx
spec:
  containers:
    - name: mikey-cont1
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
    - name: mikey-cont2
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          protocol: TCP