apiVersion: v1
kind: Service
metadata:
  name: mikey-svc
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - targetPort: 8080
      port: 35000
      nodePort: 32760
  type: NodePort