apiVersion: v1
kind: ReplicationController
metadata:
  name: mikey-rc
  labels:
    app: nginx
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: mikey-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: mikey-cont1
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP