apiVersion: v1
kind: ReplicationController
metadata:
  name: mikey-rc1
  labels:
    app: nginx
spec:
  minReadySeconds: 3
  replicas: 5
  selector:
    app: nginx
  template:
    metadata:
      name: mikey-pod
      labels:
        app: nginx
        ver: "1.0"
    spec:
      containers:
        - name: mikey-cont
          image: httpd
          ports:
            - containerPort: 80
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: mikey-svc
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 35000
  selector:
    app: nginx