---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mikey-rs
  labels:
    app: jenkins
spec:
  minReadySeconds: 5
  replicas: 5
  selector:
    matchExpressions:
      - key: app
        operator: DoesNotExists
  template:
    metadata:
      name: mikey-pod
      labels:
        app: jenkins
    spec:
      containers:
        - name: mikey-cont
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
