---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mikey-rs
  labels:
    app: nginx
spec:
  minReadySeconds: 5
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: mikey-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: mikey-cont
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests: 
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "500"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mikey-svc
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 35000
  selector:
    app: nginx
