apiVersion: v1
kind: ReplicationController
metadata:
  name: mikey-rc
  labels:
    app: nginx
spec:
  minReadySeconds: 3
  replicas: 5
  template:
    metadata:
      name: mikey-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: mikey-cont
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP